### PR TITLE
Updated yts url

### PR DESCRIPTION
**Pull request by ishaansaxena25**

### CODE REVIEW

**Comment by sambhavsaxena** [comment]
@ishaansaxena25 what's the point of closing it without merge?

**Comment by ishaansaxena25** [comment]
because it didn't matter.
although yts.mx is the official page ;)

**Comment by sambhavsaxena** [comment]
no yts page is official, its just another pirated content distributor

**Comment by ishaansaxena25** [comment]
Daddy chill

**Pull request closed without merging**
